# Generated by Django 5.0.14 on 2026-10-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_incial', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('saldo_esperado', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('saldo_real', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('concepto', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'movimientos_caja',
                'managed': False,
            },
        ),
    ]
