# Generated by Django 5.0.14 on 2026-10-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquileres',
            fields=[
                ('id_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('importe_acordado', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alquileres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apertura',
            fields=[
                ('id_apertura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'apertura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagosAlquileres',
            fields=[
                ('id_pago_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pagos_alquileres',
                'managed': False,
            },
        ),
    ]
