# Generated by Django 5.0.14 on 2026-10-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosTurnos',
            fields=[
                ('id_servicio_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios_turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
    ]
