# Generated by Django 5.0.14 on 2026-10-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('apellido', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
